sudo: false
language: node_js
node_js:
  - node
  - "6"
before_install: npm install --global npm
script: npm run-script pretest && npm run-script coverage
after_script: nyc report --reporter=text-lcov | npx coveralls
